
# ***Análisis de Datos y Big data***

## ***Universidad de los Andes***
>## **Dirección de Educación Continua.**
>>## **Formación de habilidades escenciales.**

# ***Procesamiento de Medium Data en Python***
# Clase 17

Hoy vamos a explorar la librería Polars y su comparación con Pandas.
También trabajaremos con el concepto de "Medium Data" y realizaremos ejercicios prácticos, incluyendo la conexión a una API para obtener datos abiertos en tiempo real.

![](https://w7.pngwing.com/pngs/838/716/png-transparent-we-bare-bears-characters-polar-bear-giant-panda-grizzly-bear-mammal-polar-bear-white-animals-cat-like-mammal.png)

In [1]:
pip install --upgrade numpy pandas

Requirement already satisfied: numpy in c:\users\roygo\appdata\local\programs\python\python312\lib\site-packages (1.26.4)
Collecting numpy
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/2d/57/8aeaf160312f7f489dea47ab61e430b5cb051f59a98ae68b7133ce8fa06a/numpy-2.3.5-cp312-cp312-win_amd64.whl.metadata
  Downloading numpy-2.3.5-cp312-cp312-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 131.3 kB/s eta 0:00:01
     ------------ ------------------------- 20.5/60.9 kB 131.3 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/60.9 kB 146.3 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/60.9 kB 146.3 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 187.9 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 202.8 kB/s eta 0:00:00
Requirement already satisfied: pandas in c:\users\roygo\appdata\local\programs\python\python312\lib\site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\roygo\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\roygo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\roygo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\roygo\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading numpy-2.3.5-cp312-cp312-win_amd64.whl (12.8 MB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB 640.0 kB/s eta 0:00:20
   ---------------------------------------- 0.0/12.8 MB 640.0 kB/s eta 0:00:20
   ---------------------------------------- 0.1/12.8 MB 558.5 kB/s eta 0:00:23
   ---------------------------------------- 0.1/12.8 MB 521.8 kB/s eta 0:00:25
   ---------------------------------------- 0.1/12.8 MB 502.0 kB/s eta 0:00:26
   ---------------------------------------- 0.1/12.8 MB 502.0 kB/s eta 0:00:26
   ---------------------------------------- 0.1/12.8 MB 399.4 kB/s eta 0:00:32
   ---------------------------------------- 0.1/12.8 MB 425.3 kB/s eta 0:00:30
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
   ---------------------------------------- 0.2/12.8 MB 416.7 kB/s eta 0:00:31
    --------------------------------------- 0.2/12.8 MB 106.9 kB/s eta 0:01:58
    --------------------------------------- 0.2/12.8 MB 106.9 kB/s eta 0:01:58
    --------------------------------------- 0.2/12.8 MB 106.9 kB/s eta 0:01:58
    --------------------------------------- 0.2/12.8 MB 106.9 kB/s eta 0:01:58
    --------------------------------------- 0.2/12.8 MB 106.9 kB/s eta 0:01:58
    --------------------------------------- 0.2/12.8 MB 106.9 kB/s eta 0:01:58
    --------------------------------------- 0.2/12.8 MB 106.9 kB/s eta 0:01:58
    --------------------------------------- 0.2/12.8 MB 106.9 kB/s eta 0:01:58
    --------------------------------------- 0.2/12.8 MB 106.9 kB/s eta 0:01:58
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.2/12.8 MB 103.8 kB/s eta 0:02:02
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 86.4 kB/s eta 0:02:25
    --------------------------------------- 0.3/12.8 MB 62.6 kB/s eta 0:03:20
    --------------------------------------- 0.3/12.8 MB 62.6 kB/s eta 0:03:20
    --------------------------------------- 0.3/12.8 MB 62.6 kB/s eta 0:03:20
    --------------------------------------- 0.3/12.8 MB 62.6 kB/s eta 0:03:20
    --------------------------------------- 0.3/12.8 MB 62.6 kB/s eta 0:03:20
    --------------------------------------- 0.3/12.8 MB 62.6 kB/s eta 0:03:20
    --------------------------------------- 0.3/12.8 MB 62.6 kB/s eta 0:03:20
    --------------------------------------- 0.3/12.8 MB 62.6 kB/s eta 0:03:20
   - -------------------------------------- 0.3/12.8 MB 62.8 kB/s eta 0:03:19
   - -------------------------------------- 0.3/12.8 MB 62.8 kB/s eta 0:03:19
   - -------------------------------------- 0.4/12.8 MB 65.5 kB/s eta 0:03:10
   - -------------------------------------- 0.4/12.8 MB 65.5 kB/s eta 0:03:10
   - -------------------------------------- 0.4/12.8 MB 65.5 kB/s eta 0:03:10
   - -------------------------------------- 0.4/12.8 MB 65.5 kB/s eta 0:03:10
   - -------------------------------------- 0.4/12.8 MB 65.7 kB/s eta 0:03:09
   - -------------------------------------- 0.4/12.8 MB 65.7 kB/s eta 0:03:09
   - -------------------------------------- 0.4/12.8 MB 69.7 kB/s eta 0:02:58
   - -------------------------------------- 0.4/12.8 MB 69.7 kB/s eta 0:02:58
   - -------------------------------------- 0.4/12.8 MB 74.4 kB/s eta 0:02:46
   - -------------------------------------- 0.5/12.8 MB 77.4 kB/s eta 0:02:40
   - -------------------------------------- 0.5/12.8 MB 77.4 kB/s eta 0:02:40
   - -------------------------------------- 0.5/12.8 MB 78.4 kB/s eta 0:02:38
   - -------------------------------------- 0.5/12.8 MB 83.0 kB/s eta 0:02:29
   - -------------------------------------- 0.5/12.8 MB 83.0 kB/s eta 0:02:29
   - -------------------------------------- 0.5/12.8 MB 83.0 kB/s eta 0:02:29
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 84.9 kB/s eta 0:02:25
   - -------------------------------------- 0.5/12.8 MB 79.4 kB/s eta 0:02:35
   - -------------------------------------- 0.5/12.8 MB 79.4 kB/s eta 0:02:35
   - -------------------------------------- 0.5/12.8 MB 79.4 kB/s eta 0:02:35
   - -------------------------------------- 0.5/12.8 MB 79.4 kB/s eta 0:02:35
   - -------------------------------------- 0.5/12.8 MB 79.4 kB/s eta 0:02:35
   - -------------------------------------- 0.6/12.8 MB 82.9 kB/s eta 0:02:28
   - -------------------------------------- 0.6/12.8 MB 82.9 kB/s eta 0:02:28
   - -------------------------------------- 0.6/12.8 MB 82.9 kB/s eta 0:02:28
   - -------------------------------------- 0.6/12.8 MB 82.9 kB/s eta 0:02:28
   - -------------------------------------- 0.6/12.8 MB 82.9 kB/s eta 0:02:28
   - -------------------------------------- 0.6/12.8 MB 82.9 kB/s eta 0:02:28
   - -------------------------------------- 0.6/12.8 MB 82.9 kB/s eta 0:02:28
   - -------------------------------------- 0.6/12.8 MB 82.6 kB/s eta 0:02:28
   - -------------------------------------- 0.6/12.8 MB 82.6 kB/s eta 0:02:28
   - -------------------------------------- 0.6/12.8 MB 84.4 kB/s eta 0:02:25
   - -------------------------------------- 0.6/12.8 MB 84.4 kB/s eta 0:02:25
   - -------------------------------------- 0.6/12.8 MB 85.3 kB/s eta 0:02:23
   -- ------------------------------------- 0.6/12.8 MB 87.6 kB/s eta 0:02:19
   -- ------------------------------------- 0.7/12.8 MB 88.6 kB/s eta 0:02:17
   -- ------------------------------------- 0.7/12.8 MB 91.0 kB/s eta 0:02:14
   -- ------------------------------------- 0.7/12.8 MB 92.8 kB/s eta 0:02:11
   -- ------------------------------------- 0.7/12.8 MB 96.4 kB/s eta 0:02:06
   -- ------------------------------------- 0.7/12.8 MB 97.3 kB/s eta 0:02:04
   -- ------------------------------------- 0.7/12.8 MB 97.3 kB/s eta 0:02:04
   -- ------------------------------------- 0.8/12.8 MB 99.2 kB/s eta 0:02:02
   -- ------------------------------------- 0.8/12.8 MB 102.5 kB/s eta 0:01:58
   -- ------------------------------------- 0.8/12.8 MB 102.5 kB/s eta 0:01:58
   -- ------------------------------------- 0.8/12.8 MB 104.3 kB/s eta 0:01:55
   -- ------------------------------------- 0.8/12.8 MB 105.2 kB/s eta 0:01:54
   -- ------------------------------------- 0.8/12.8 MB 107.5 kB/s eta 0:01:52
   -- ------------------------------------- 0.9/12.8 MB 109.7 kB/s eta 0:01:49
   -- ------------------------------------- 0.9/12.8 MB 110.1 kB/s eta 0:01:49
   -- ------------------------------------- 0.9/12.8 MB 112.5 kB/s eta 0:01:46
   -- ------------------------------------- 0.9/12.8 MB 113.3 kB/s eta 0:01:45
   -- ------------------------------------- 0.9/12.8 MB 115.0 kB/s eta 0:01:44
   -- ------------------------------------- 0.9/12.8 MB 117.4 kB/s eta 0:01:41
   -- ------------------------------------- 1.0/12.8 MB 118.0 kB/s eta 0:01:41
   --- ------------------------------------ 1.0/12.8 MB 120.9 kB/s eta 0:01:38
   --- ------------------------------------ 1.0/12.8 MB 121.7 kB/s eta 0:01:37
   --- ------------------------------------ 1.0/12.8 MB 121.7 kB/s eta 0:01:37
   --- ------------------------------------ 1.0/12.8 MB 123.5 kB/s eta 0:01:36
   --- ------------------------------------ 1.0/12.8 MB 126.3 kB/s eta 0:01:33
   --- ------------------------------------ 1.1/12.8 MB 128.1 kB/s eta 0:01:32
   --- ------------------------------------ 1.1/12.8 MB 128.8 kB/s eta 0:01:31
   --- ------------------------------------ 1.1/12.8 MB 130.6 kB/s eta 0:01:30
   --- ------------------------------------ 1.1/12.8 MB 131.1 kB/s eta 0:01:30
   --- ------------------------------------ 1.1/12.8 MB 131.1 kB/s eta 0:01:30
   --- ------------------------------------ 1.1/12.8 MB 133.7 kB/s eta 0:01:28
   --- ------------------------------------ 1.2/12.8 MB 135.7 kB/s eta 0:01:26
   --- ------------------------------------ 1.2/12.8 MB 137.6 kB/s eta 0:01:25
   --- ------------------------------------ 1.2/12.8 MB 137.6 kB/s eta 0:01:25
   --- ------------------------------------ 1.2/12.8 MB 139.9 kB/s eta 0:01:23
   --- ------------------------------------ 1.2/12.8 MB 141.5 kB/s eta 0:01:22
   --- ------------------------------------ 1.2/12.8 MB 141.5 kB/s eta 0:01:22
   --- ------------------------------------ 1.3/12.8 MB 143.8 kB/s eta 0:01:21
   --- ------------------------------------ 1.3/12.8 MB 143.8 kB/s eta 0:01:21
   --- ------------------------------------ 1.3/12.8 MB 143.8 kB/s eta 0:01:21
   --- ------------------------------------ 1.3/12.8 MB 143.7 kB/s eta 0:01:21
   ---- ----------------------------------- 1.3/12.8 MB 147.6 kB/s eta 0:01:18
   ---- ----------------------------------- 1.3/12.8 MB 147.6 kB/s eta 0:01:18
   ---- ----------------------------------- 1.3/12.8 MB 147.6 kB/s eta 0:01:18
   ---- ----------------------------------- 1.3/12.8 MB 146.9 kB/s eta 0:01:19
   ---- ----------------------------------- 1.3/12.8 MB 148.7 kB/s eta 0:01:17
   ---- ----------------------------------- 1.4/12.8 MB 149.3 kB/s eta 0:01:17
   ---- ----------------------------------- 1.4/12.8 MB 151.1 kB/s eta 0:01:16
   ---- ----------------------------------- 1.4/12.8 MB 152.0 kB/s eta 0:01:15
   ---- ----------------------------------- 1.4/12.8 MB 152.0 kB/s eta 0:01:15
   ---- ----------------------------------- 1.4/12.8 MB 152.3 kB/s eta 0:01:15
   ---- ----------------------------------- 1.4/12.8 MB 154.6 kB/s eta 0:01:14
   ---- ----------------------------------- 1.5/12.8 MB 156.3 kB/s eta 0:01:13
   ---- ----------------------------------- 1.5/12.8 MB 157.5 kB/s eta 0:01:12

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\roygo\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: Could not install packages due to an OSError: [WinError 5] Acceso denegado: 'C:\\Users\\roygo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\~%mpy.libs\\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import polars as pl
import time
import requests  # Nueva librería para trabajar con la API

# Configurar opciones de pandas para mejor visualización
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# "Medium Data" 

Se refiere a conjuntos de datos que no son lo suficientemente grandes como para necesitar herramientas de Big Data, pero que pueden ser demasiado grandes para ser manejados de manera eficiente con herramientas tradicionales como Pandas.

# Pregunta: 
- ¿Qué tamaño de datos manejas comúnmente en tus proyectos?
- ¿En qué casos has experimentado problemas de rendimiento con Pandas?

- **Tamaño y Escala:** Los datos de tamaño medio son más grandes y complejos que los pequeños conjuntos de datos (como una hoja de cálculo con registros de clientes de una pequeña empresa), pero no alcanzan el volumen o la variedad de Big Data (como los generados por redes sociales a nivel global o sensores de IoT a gran escala).

- **Características:** Estos datos pueden incluir diversas fuentes y tipos, pero aún son manejables con herramientas y tecnologías de análisis de datos estándar. Pueden requerir cierto grado de procesamiento y capacidad de almacenamiento, pero no en la misma medida que el Big Data.

- **Escalabilidad:** Un desafío clave es la escalabilidad. A medida que una organización crece, sus datos pueden empezar a acercarse al umbral del Big Data, lo que requiere una reevaluación de las herramientas y estrategias de manejo de datos.

### Pandas

- **Biblioteca de Código Abierto:** Escrita en Python, proporciona estructuras de datos de alto rendimiento y herramientas de análisis.
- **Estructuras de Datos:** Ofrece dos estructuras principales, Series (unidimensional) y DataFrame (bidimensional).
- **Manipulación y Análisis de Datos:** Ideal para limpieza, transformación, agregación y visualización de datos.
- **Lectura y Escritura de Datos:** Soporta varios formatos como CSV, Excel, SQL, entre otros.
- **Uso de NumPy:** Tradicionalmente, ha utilizado NumPy para operaciones de bajo nivel y manipulación de arrays.

## Polars

Puedes ver más en [Cheat seet](https://franzdiebold.github.io/polars-cheat-sheet/Polars_cheat_sheet.pdf).

Polars combina la flexibilidad y facilidad de uso de Python con la velocidad y escalabilidad de Rust. Es rápido gracias a su núcleo escrito en Rust, un lenguaje eficiente en memoria con rendimiento comparable a C o C++. Polars puede utilizar todos los núcleos de CPU en paralelo y admite conjuntos de datos grandes. Su API intuitiva es fácil de usar para quienes conocen bibliotecas como Pandas. Además, utiliza Apache Arrow para ejecutar consultas vectorizadas y almacenamiento de datos columnar para un procesamiento en memoria rápido. Estas características lo hacen una biblioteca atractiva para el procesamiento de datos.

----

Vamos a cargar los datos que se encuentran en:`https://j.mp/iriscsv`

In [3]:
# Cargar un archivo CSV con Pandas
start_time = time.time()
df_pandas = pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')
end_time = time.time()
print(f"Pandas cargó los datos en {end_time - start_time} segundos.")

# Cargar un archivo CSV con Polars
start_time = time.time()
df_polars = pl.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')
end_time = time.time()
print(f"Polars cargó los datos en {end_time - start_time} segundos.")

Pandas cargó los datos en 0.7870492935180664 segundos.
Polars cargó los datos en 0.47908496856689453 segundos.

### Pregunta: 
¿Qué diferencias observas en los tiempos de carga?

### URL de la API de datos abiertos

In [6]:
import requests
import time

url = "https://jsonplaceholder.typicode.com/posts"

start_time = time.time()
response = requests.get(url, timeout=10)
end_time = time.time()

data_json = response.json()

print(f"Tiempo de respuesta: {end_time - start_time:.4f} segundos")
print(f"Número de registros: {len(data_json)}")

Tiempo de respuesta: 0.3503 segundos
Número de registros: 100

In [8]:
import pandas as pd

df_api_pandas = pd.DataFrame(data_json)
df_api_pandas.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [9]:
df_api_pandas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   userId  100 non-null    int64
 1   id      100 non-null    int64
 2   title   100 non-null    object
 3   body    100 non-null    object
dtypes: int64(2), object(2)
memory usage: 3.3+ KB

In [10]:
df_api_pandas['title']

0     sunt aut facere repellat provident occaecati e...
1                                          qui est esse
2     ea molestias quasi exercitationem repellat qui...
3                                  eum et est occaecati
4                                    nesciunt quas odio
5                    dolorem eum magni eos aperiam quia
6                                  magnam facilis autem
7                              dolorem dolore est ipsam
8     nesciunt iure omnis dolorem tempora et accusan...
9                           optio molestias id quia eum
10                     et ea vero quia laudantium autem
11                in quibusdam tempore odit est dolorem
12    dolorum ut in voluptas mollitia et saepe quo a...
13                            voluptatem eligendi optio
14                              eveniet quod temporibus
15    sint suscipit perspiciatis velit dolorum rerum...
16    fugit voluptas sed molestias voluptatem provident
17           voluptate et itaque vero tempora molestiae
18            adipisci placeat illum aut reiciendis qui
19                   doloribus ad provident suscipit at
20    asperiores ea ipsam voluptatibus modi minima q...
21            dolor sint quo a velit explicabo quia nam
22                        maxime id vitae nihil numquam
23               autem hic labore sunt dolores incidunt
24                        rem alias distinctio quo quis
25                             est et quae odit qui non
26                quasi id et eos tenetur aut quo autem
27      delectus ullam et corporis nulla voluptas sequi
28              iusto eius quod necessitatibus culpa ea
29                    a quo magni similique perferendis
30              ullam ut quidem id aut vel consequuntur
31                        doloremque illum aliquid sunt
32                      qui explicabo molestiae dolorem
33                                 magnam ut rerum iure
34       id nihil consequatur molestias animi provident
35        fuga nam accusamus voluptas reiciendis itaque
36                     provident vel ut sit ratione est
37    explicabo et eos deleniti nostrum ab id repell...
38          eos dolorem iste accusantium est eaque quam
39                                      enim quo cumque
40                                       non est facere
41    commodi ullam sint et excepturi error explicab...
42    eligendi iste nostrum consequuntur adipisci pr...
43                            optio dolor molestias sit
44    ut numquam possimus omnis eius suscipit laudan...
45                   aut quo modi neque nostrum ducimus
46                    quibusdam cumque rem aut deserunt
47          ut voluptatem illum ea doloribus itaque eos
48    laborum non sunt aut ut assumenda perspiciatis...
49    repellendus qui recusandae incidunt voluptates...
50    soluta aliquam aperiam consequatur illo quis v...
51    qui enim et consequuntur quia animi quis volup...
52                             ut quo aut ducimus alias
53           sit asperiores ipsam eveniet odio non quia
54                     sit vel voluptatem et non libero
55                       qui et at rerum necessitatibus
56                                       sed ab est est
57              voluptatum itaque dolores nisi et quasi
58    qui commodi dolor at maiores et quis id accusa...
59    consequatur placeat omnis quisquam quia repreh...
60      voluptatem doloribus consectetur est ut ducimus
61                                 beatae enim quia vel
62    voluptas blanditiis repellendus animi ducimus ...
63                 et fugit quas eum in in aperiam quod
64                       consequatur id enim sunt et et
65                           repudiandae ea animi iusto
66          aliquid eos sed fuga est maxime repellendus
67         odio quis facere architecto reiciendis optio
68                     fugiat quod pariatur odit minima
69                             voluptatem laborum magni
70                    et iusto veniam et illum aut fuga
71            sint hic doloribus consequatur eos non id
72    consequuntur deleniti eos quia temporibus ab a...
73    enim unde ratione doloribus quas enim ut sit s...
74         dignissimos eum dolor ut enim et delectus in
75            doloremque officiis ad et non perferendis
76             necessitatibus quasi exercitationem odio
77                    quam voluptatibus rerum veritatis
78    pariatur consequatur quia magnam autem omnis n...
79          labore in ex et explicabo corporis aut quas
80      tempora rem veritatis voluptas quo dolores vero
81         laudantium voluptate suscipit sunt enim enim
82           odit et voluptates doloribus alias odio et
83    optio ipsam molestias necessitatibus occaecati...
84    dolore veritatis porro provident adipisci blan...
85                           placeat quia et porro iste
86                           nostrum quis quasi placeat
87                             sapiente omnis fugit eos
88             sint soluta et vel magnam aut ut sed qui
89               ad iusto omnis odit dolor voluptatibus
90                                         aut amet sed
91                       ratione ex tenetur perferendis
92                             beatae soluta recusandae
93                  qui qui voluptates illo iste minima
94                id minus libero illum nam ad officiis
95    quaerat velit veniam amet cupiditate aut numqu...
96           quas fugiat ut perspiciatis vero provident
97                          laboriosam dolor voluptates
98    temporibus sit alias delectus eligendi possimu...
99                at nam consequatur ea labore ea harum
Name: title, dtype: object

In [11]:
# Convertir la respuesta en un DataFrame de Polars
df_api_polars = pl.DataFrame(data_json)
df_api_polars.head()

shape: (5, 4)
┌────────┬─────┬─────────────────────────────────┬─────────────────────────────────┐
│ userId ┆ id  ┆ title                           ┆ body                            │
│ ---    ┆ --- ┆ ---                             ┆ ---                             │
│ i64    ┆ i64 ┆ str                             ┆ str                             │
╞════════╪═════╪═════════════════════════════════╪═════════════════════════════════╡
│ 1      ┆ 1   ┆ sunt aut facere repellat provi… ┆ quia et suscipit                │
│        ┆     ┆                                 ┆ suscipit recu…                  │
│ 1      ┆ 2   ┆ qui est esse                    ┆ est rerum tempore vitae         │
│        ┆     ┆                                 ┆ sequi …                         │
│ 1      ┆ 3   ┆ ea molestias quasi exercitatio… ┆ et iusto sed quo iure           │
│        ┆     ┆                                 ┆ voluptat…                       │
│ 1      ┆ 4   ┆ eum et est occaecati            ┆ ullam et saepe reiciendis volu… │
│ 1      ┆ 5   ┆ nesciunt quas odio              ┆ repudiandae veniam quaerat sun… │
└────────┴─────┴─────────────────────────────────┴─────────────────────────────────┘

### Pregunta: 
¿Qué diferencias encuentras en el manejo de los datos provenientes de una API con Pandas y Polars?

### Operación de Filtrado en Pandas

In [12]:
df_api_pandas['title']

0     sunt aut facere repellat provident occaecati e...
1                                          qui est esse
2     ea molestias quasi exercitationem repellat qui...
3                                  eum et est occaecati
4                                    nesciunt quas odio
5                    dolorem eum magni eos aperiam quia
6                                  magnam facilis autem
7                              dolorem dolore est ipsam
8     nesciunt iure omnis dolorem tempora et accusan...
9                           optio molestias id quia eum
10                     et ea vero quia laudantium autem
11                in quibusdam tempore odit est dolorem
12    dolorum ut in voluptas mollitia et saepe quo a...
13                            voluptatem eligendi optio
14                              eveniet quod temporibus
15    sint suscipit perspiciatis velit dolorum rerum...
16    fugit voluptas sed molestias voluptatem provident
17           voluptate et itaque vero tempora molestiae
18            adipisci placeat illum aut reiciendis qui
19                   doloribus ad provident suscipit at
20    asperiores ea ipsam voluptatibus modi minima q...
21            dolor sint quo a velit explicabo quia nam
22                        maxime id vitae nihil numquam
23               autem hic labore sunt dolores incidunt
24                        rem alias distinctio quo quis
25                             est et quae odit qui non
26                quasi id et eos tenetur aut quo autem
27      delectus ullam et corporis nulla voluptas sequi
28              iusto eius quod necessitatibus culpa ea
29                    a quo magni similique perferendis
30              ullam ut quidem id aut vel consequuntur
31                        doloremque illum aliquid sunt
32                      qui explicabo molestiae dolorem
33                                 magnam ut rerum iure
34       id nihil consequatur molestias animi provident
35        fuga nam accusamus voluptas reiciendis itaque
36                     provident vel ut sit ratione est
37    explicabo et eos deleniti nostrum ab id repell...
38          eos dolorem iste accusantium est eaque quam
39                                      enim quo cumque
40                                       non est facere
41    commodi ullam sint et excepturi error explicab...
42    eligendi iste nostrum consequuntur adipisci pr...
43                            optio dolor molestias sit
44    ut numquam possimus omnis eius suscipit laudan...
45                   aut quo modi neque nostrum ducimus
46                    quibusdam cumque rem aut deserunt
47          ut voluptatem illum ea doloribus itaque eos
48    laborum non sunt aut ut assumenda perspiciatis...
49    repellendus qui recusandae incidunt voluptates...
50    soluta aliquam aperiam consequatur illo quis v...
51    qui enim et consequuntur quia animi quis volup...
52                             ut quo aut ducimus alias
53           sit asperiores ipsam eveniet odio non quia
54                     sit vel voluptatem et non libero
55                       qui et at rerum necessitatibus
56                                       sed ab est est
57              voluptatum itaque dolores nisi et quasi
58    qui commodi dolor at maiores et quis id accusa...
59    consequatur placeat omnis quisquam quia repreh...
60      voluptatem doloribus consectetur est ut ducimus
61                                 beatae enim quia vel
62    voluptas blanditiis repellendus animi ducimus ...
63                 et fugit quas eum in in aperiam quod
64                       consequatur id enim sunt et et
65                           repudiandae ea animi iusto
66          aliquid eos sed fuga est maxime repellendus
67         odio quis facere architecto reiciendis optio
68                     fugiat quod pariatur odit minima
69                             voluptatem laborum magni
70                    et iusto veniam et illum aut fuga
71            sint hic doloribus consequatur eos non id
72    consequuntur deleniti eos quia temporibus ab a...
73    enim unde ratione doloribus quas enim ut sit s...
74         dignissimos eum dolor ut enim et delectus in
75            doloremque officiis ad et non perferendis
76             necessitatibus quasi exercitationem odio
77                    quam voluptatibus rerum veritatis
78    pariatur consequatur quia magnam autem omnis n...
79          labore in ex et explicabo corporis aut quas
80      tempora rem veritatis voluptas quo dolores vero
81         laudantium voluptate suscipit sunt enim enim
82           odit et voluptates doloribus alias odio et
83    optio ipsam molestias necessitatibus occaecati...
84    dolore veritatis porro provident adipisci blan...
85                           placeat quia et porro iste
86                           nostrum quis quasi placeat
87                             sapiente omnis fugit eos
88             sint soluta et vel magnam aut ut sed qui
89               ad iusto omnis odit dolor voluptatibus
90                                         aut amet sed
91                       ratione ex tenetur perferendis
92                             beatae soluta recusandae
93                  qui qui voluptates illo iste minima
94                id minus libero illum nam ad officiis
95    quaerat velit veniam amet cupiditate aut numqu...
96           quas fugiat ut perspiciatis vero provident
97                          laboriosam dolor voluptates
98    temporibus sit alias delectus eligendi possimu...
99                at nam consequatur ea labore ea harum
Name: title, dtype: object

In [ ]:
df_pandas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [13]:
df_pandas['sepal_length'].value_counts()

sepal_length
5.0    10
6.3     9
5.1     9
6.7     8
5.7     8
6.4     7
5.5     7
5.8     7
4.9     6
6.0     6
5.4     6
5.6     6
6.1     6
6.5     5
4.8     5
7.7     4
6.9     4
4.6     4
5.2     4
6.2     4
4.4     3
7.2     3
5.9     3
6.8     3
4.7     2
6.6     2
4.3     1
7.0     1
5.3     1
4.5     1
7.1     1
7.3     1
7.6     1
7.4     1
7.9     1
Name: count, dtype: int64

In [ ]:
start_time = time.time()
filtered_pandas = df_pandas[(df_pandas['petal_length'] > 3.1)&(df_pandas['sepal_length'] > 4.2)]
end_time = time.time()
print(f"Filtrado en Pandas tomó {end_time - start_time} segundos.")

Filtrado en Pandas tomó 0.002016305923461914 segundos.

### Operación de Filtrado en Polars

In [ ]:
start_time = time.time()
filtered_polars = df_polars.filter((pl.col('petal_length') > 3.1)&(pl.col('sepal_length')>4.2))
end_time = time.time()
print(f"Filtrado en Polars tomó {end_time - start_time} segundos.")

Filtrado en Polars tomó 0.0010077953338623047 segundos.

ALgunas de las funciones que son posibles usar son

| Función | Descripción |
|---------|-------------|
| `sum()` | Calcula la suma de los valores de la columna. |
| `mean()` | Calcula el promedio de los valores de la columna. |
| `min()` | Encuentra el valor mínimo en la columna. |
| `max()` | Encuentra el valor máximo en la columna. |
| `count()` | Cuenta el número de elementos en la columna. |
| `median()` | Calcula la mediana de los valores de la columna. |
| `std()` | Calcula la desviación estándar de los valores de la columna. |
| `var()` | Calcula la varianza de los valores de la columna. |
| `quantile(q)` | Calcula el cuantil (por ejemplo, mediana para `q=0.5`). |
| `first()` | Obtiene el primer valor de la columna en un grupo. |
| `last()` | Obtiene el último valor de la columna en un grupo. |
| `unique()` | Devuelve valores únicos de la columna. |
| `list()` | Agrega los valores de la columna en una lista (útil en agrupaciones). |
| `sort()` | Ordena los valores de la columna. |
| `apply(func)` | Aplica una función personalizada a los valores de la columna. |
| `is_null()` | Devuelve una máscara booleana indicando si los valores son nulos. |
| `is_not_null()` | Devuelve una máscara booleana indicando si los valores no son nulos. |
| `is_finite()` | Comprueba si los valores son finitos. |
| `is_infinite()` | Comprueba si los valores son infinitos. |
| `clip(min_val, max_val)` | Limita los valores a un rango definido. |
| `alias(new_name)` | Renombra la columna (útil en agrupaciones y selecciones). |



| Operador | Descripción                                     |
|----------|-------------------------------------------------|
| `&`      | Operador lógico `AND` (Y lógico). Combina dos o más condiciones y todas deben ser verdaderas. |
| `\|`      | Operador lógico `OR` (O lógico). Combina dos o más condiciones y al menos una debe ser verdadera. |
| `~`      | Operador lógico `NOT` (NO lógico). Niega una condición, invirtiendo su resultado. |

### Pregunta: 
¿Cuál fue la diferencia en el tiempo de ejecución entre Pandas y Polars?

### Agrupar y agregar datos en Pandas

In [ ]:
df_pandas.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
start_time = time.time()
grouped_pandas = df_pandas.groupby('species').agg({'sepal_length': 'mean', 'petal_length': 'std','petal_width':'sum'})
end_time = time.time()
print(f"Group by en Pandas tomó {end_time - start_time} segundos.")

Group by en Pandas tomó 0.003018617630004883 segundos.

In [ ]:
grouped_pandas

            sepal_length  petal_length
species
setosa             5.006      0.173511
versicolor         5.936      0.469911
virginica          6.588      0.551895

### Agrupar y agregar datos en Polars

In [ ]:

start_time = time.time()
grouped_polars = df_polars.groupby('species').agg(pl.col('sepal_length').mean(),pl.col('petal_length').std(),pl.col('petal_width').sum() )
end_time = time.time()
print(f"Group by en Polars tomó {end_time - start_time} segundos.")

Group by en Polars tomó 0.004995822906494141 segundos.

C:\Users\roygo\AppData\Local\Temp\ipykernel_28104\3476840857.py:2: DeprecationWarning: `groupby` is deprecated. It has been renamed to `group_by`.
  grouped_polars = df_polars.groupby('species').agg(pl.col('sepal_length').mean(),pl.col('petal_length').std(),pl.col('petal_width').sum() )

In [ ]:
grouped_polars

shape: (3, 3)
┌────────────┬──────────────┬──────────────┐
│ species    ┆ sepal_length ┆ petal_length │
│ ---        ┆ ---          ┆ ---          │
│ str        ┆ f64          ┆ f64          │
╞════════════╪══════════════╪══════════════╡
│ setosa     ┆ 5.006        ┆ 0.173511     │
│ virginica  ┆ 6.588        ┆ 0.551895     │
│ versicolor ┆ 5.936        ┆ 0.469911     │
└────────────┴──────────────┴──────────────┘

### Pregunta: ¿Notaste alguna diferencia en la sintaxis o el tiempo de ejecución?

A lo largo de este taller, hemos comparado las librerías Pandas y Polars en términos de carga, filtrado, agrupación, manejo de datos en tiempo real desde una API, y rendimiento.

### Pregunta final: ¿En qué casos considerarías usar Polars en lugar de Pandas en tus proyectos?

### Comparación


#### Lectura de datos
![](https://miro.medium.com/v2/resize:fit:828/format:webp/1*HWibbnVYohpKbpjMmL15rw.png)

#### Operaciones de agregación
![](https://miro.medium.com/v2/resize:fit:828/format:webp/1*7-xfg0arCNVTv4AG3yzTwg.png)

#### Filtros y selección

![](https://miro.medium.com/v2/resize:fit:828/format:webp/1*XR09526SmAUHrBwr0lfFzg.png)

#### Operación de clasificación
![](https://miro.medium.com/v2/resize:fit:828/format:webp/1*Blya6y4zfInlBPe-u2nOEA.png)

### Puedes ver más información

1. https://github.com/pola-rs/polars
2. https://medium.com/cuenex/pandas-2-0-vs-polars-the-ultimate-battle-a378eb75d6d1
3. https://docs.pola.rs/user-guide/